// USERS
const admin = new User('Admin', 'admin', 'admin');
const user1 = new User('Phan Trung Hiếu', 'phantrunghieu1291@gmail.com', '12345');

const usersList = [admin, user1];

// DISCOUNT CODE
const discountCodeList = [{book10: 10}, {book20: 20}];

// CITY
const citiesList = ['An Giang', 'Bà Rịa - Vũng Tàu', 'Bạc Liêu', 'Bắc Giang', 'Bắc Kạn', 'Bắc Ninh', 'Bến Tre', 'Bình Dương', 'Bình Định', 'Bình Phước', 'Bình Thuận', 'Cà Mau', 'Cao Bằng', 'Cần Thơ', 'Đà Nẵng', 'Đăk Lăk', 'Đăk Nông', 'Điện Biên', 'Đồng Nai', 'Đồng Tháp', 'Gia Lai', 'Hà Giang', 'Hà Nam', 'Hà Nội', 'Hà Tỉnh', 'Hải Dương', 'Hải Phòng', 'Hậu Giang', 'Hòa Bình', 'TP.Hồ Chí Minh', 'Hưng Yên', 'Khánh Hòa', 'Kiên Giang', 'Kom Tum', 'Lai Châu', 'Lạng Sơn', 'Lào Cai', 'Lâm Đồng', 'Long An', 'Nam Định', 'Nghệ An', 'Ninh Bình', 'Ninh Thuận', 'Phú Thọ', 'Phú Yên', 'Quảng Bình', "Quảng Nam", ' Quảng Ngãi', 'Quảng Ninh', 'Quảng Trị', 'Sóc Trăng', 'Sơn La', 'Tây Ninh', 'Thái Bình', 'Thái Nguyên', 'Thanh Hóa', 'Thừa Thiên Huế', 'Tiền Giang', 'Trà Vinh', 'Tuyên Quang', 'Vĩnh Long', 'Vĩnh Phúc', 'Yên Bái'];

// BOOKS
const booksList = [
    new Book('Bé chinh phục 2000 từ vựng tiếng Anh - My First 2000 English words', 'Hà Nội', 'Amelia Smith', 'thiếu nhi', 80, `Khoa học đã chứng minh, giai đoạn 4-6 tuổi là giai đoạn vàng trong việc phát triển khả năng tiếp nhận ngôn ngữ. Ở thời điểm này, việc bé được tiếp xúc với từ vựng, mẫu câu đơn giản thông qua các giáo cụ trực quan như bài hát, hình ảnh sẽ tăng khả năng ghi nhớ ngôn ngữ lên nhiều lần. Chính vì vậy,  đội ngũ biên soạn đã dày công nghiên cứu cuốn sách “Bé Chinh phục 2000 từ vựng Tiếng Anh – Theo Sơ đồ Tư duy/Sơ đồ Concept” với hơn 45 chủ đề thường gặp trong cuộc sống, 15 bài hát – mẫu câu thông dụng, và hơn 2.000 từ vựng tiếng Anh.
    Với mong muốn giúp các bé có thêm nhiều niềm vui trong việc ghi nhớ và học từ vựng, cuốn sách được trình bày theo cả hai phương pháp minh họa – Sơ đồ Tư duy (Mind Map) và hình ảnh Chủ đề (Concept Map). Ba mẹ cũng nhờ đó có thể dễ dàng học tiếng Anh cùng con thông qua việc ghi nhớ các hình ảnh minh họa, các bài hát đính kèm theo chủ đề liên quan. Đặc biệt, cuốn sách có kèm theo File đọc từ vựng tiếng Anh giọng chuẩn bản địa, quét mã QR trên sách theo từng chủ đề, sẽ giúp trẻ luyện kĩ năng nghe tốt hơn và phát âm theo chuẩn hơn. Chúc các bé và ba mẹ học Tiếng Anh thật vui.`, `https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/1-jpeg.jpg?v=1654775653687`, 0), 
    new Book('Tiếng hàn tổng hợp dành cho người Việt Nam - Sơ cấp 1', 'Đại học quốc gia Hà Nội', 'Lê Thị Thu Giang, Đỗ Ngọc Luyến, Lee Mi Hye', 'ngoại ngữ', 220, `2 cuốn sách trong bộ Sơ cấp được xây dựng với 30 bài khóa và bảng chữ cái. Trong đó quyển 1 gồm phần bảng chữ cái và 15 bài đầu. Học hết quyển 1, bạn sẽ học đến quyển sơ cấp 2 với 15 bài còn lại. Cấu trúc tổng thể của giáo trình được xây dựng theo các chủ đề; mỗi chủ đề được liên kết thống nhất với một hệ thống các từ vựng và cấu trúc ngữ pháp cơ bản, bài tập ứng dụng, kỹ năng và tìm hiểu văn hóa. Trong mỗi bài học, nội dung học được chia thành các phần như: luyện từ vựng, luyện ngữ pháp cơ bản, luyện tập kỹ năng nghe – nói – đọc – viết, luyện phát âm, tìm hiểu văn hóa của đất nước Hàn Quốc xinh đẹp. Và kết thúc mỗi bài đều có thêm bảng từ mới xuất hiện trong bài học. Phần cuối của sách, các tác giả đưa ra hệ thống từ mới được sắp xếp theo thứ tự của bảng chữ cái. Đây là những từ không xuất hiện trong phần ngữ pháp, từ vựng cơ bản; nhưng lại xuất hiện nhiều ở phần luyện tập của từng bài.`, 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/1-ccf6a40f-a969-4bee-a658-c4f8b6fa28a5.jpg?v=1634611397220'),
    new Book('Tiếng hàn tổng hợp dành cho người Việt Nam - Sơ cấp 2', 'Đại học quốc gia Hà Nội', 'Lê Thị Thu Giang, Đỗ Ngọc Luyến, Lee Mi Hye', 'ngoại ngữ', 220, `2 cuốn sách trong bộ Sơ cấp được xây dựng với 30 bài khóa và bảng chữ cái. Trong đó quyển 1 gồm phần bảng chữ cái và 15 bài đầu. Học hết quyển 1, bạn sẽ học đến quyển sơ cấp 2 với 15 bài còn lại. Cấu trúc tổng thể của giáo trình được xây dựng theo các chủ đề; mỗi chủ đề được liên kết thống nhất với một hệ thống các từ vựng và cấu trúc ngữ pháp cơ bản, bài tập ứng dụng, kỹ năng và tìm hiểu văn hóa. Trong mỗi bài học, nội dung học được chia thành các phần như: luyện từ vựng, luyện ngữ pháp cơ bản, luyện tập kỹ năng nghe – nói – đọc – viết, luyện phát âm, tìm hiểu văn hóa của đất nước Hàn Quốc xinh đẹp. Và kết thúc mỗi bài đều có thêm bảng từ mới xuất hiện trong bài học. Phần cuối của sách, các tác giả đưa ra hệ thống từ mới được sắp xếp theo thứ tự của bảng chữ cái. Đây là những từ không xuất hiện trong phần ngữ pháp, từ vựng cơ bản; nhưng lại xuất hiện nhiều ở phần luyện tập của từng bài.`, 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/0-3ea8d999-1fdc-4d7f-a982-e1838052d1b9.jpg?v=1634611495817'),
    new Book('Thương nhớ Trà Long', 'Trẻ', 'Nguyễn Nhật Ánh', 'văn học việt nam', 65, 'Một cuốn sách lãng mạn, trong từng con chữ đầy ắp tình yêu với mưa, với lá, với ngôi nhà cũ, cuốn sách xưa, cùng nỗi nhớ quê và những kỷ niệm thuở nhỏ... Có thể thấy mùi vị của những món ăn mẹ nấu, màu sắc trái cây mẹ mua, những trò chơi của con nhà nghèo…, từ ký ức tác giả đã vẽ ra cho người đọc cả một miền quê với hình ảnh, bối cảnh, không gian, con người của thời ấy, chân thực và tinh tế.', 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/nguyen-nhat-anh-thuong-nho-tra-long.jpg?v=1544255899020'),
    new Book('Truyện ngắn Jack London', 'Văn học', 'Jack London', 'văn học nước ngoài', 88, 'Jack London là nhà vǎn tiến bộ của Mỹ ở cuối thế kỷ 19 đầu thế kỷ 20. Sinh thời ông làm đủ mọi nghề từ bán báo, công nhân, cảnh sát, hàng hải rồi thuỷ thủ... sau cùng là tìm vàng và viết vǎn. Chính từ cuộc đời đầy gian nan vất vả đó mà ông hiểu được đời sống của nhân dân lao động nghèo khổ, và cũng từ đó ông sáng tạo nên những tác phẩm độc đáo và đầy ấn tượng, phong phú, đa dạng, giàu giá trị nhân vǎn, luôn bênh vực và bảo vệ người cần lao.', 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/truyen-ngan-jack-london.jpg?v=1542792062577'),
    new Book('Thủy Hử', 'Văn học', 'Thi Nại Âm', 'văn học nước ngoài', 275, `Thủy Hử (nghĩa đen là “bến nước”) là một trong Tứ đại danh tác của văn học cổ điển Trung Quốc. Đây là pho tiểu thuyết được ưa thích và lưu truyền rộng rãi trong lịch sử, khắc họa thành công hình tượng những anh hùng hảo hán võ nghệ cao cường, giàu lòng vị tha, xả thân vì nghĩa. Cốt truyện là sự hình thành và những chiến tích của cuộc khởi nghĩa nông dân chống triều đình nhà Tống, do Tống Giang lãnh đạo. Thủy Hử phản ánh thực trạng trong xã hội phong kiến muôn đời: "quan bức thì dân phản". Và thời thế đó đã tất yếu đã sinh ra những “Anh hùng thời loạn” - những người có khả năng dựng ngọn cờ “Thế thiên hành đạo” để quy tụ lực lượng quần chúng lao khổ nhất tề đứng lên chống cường quyền áp bức, đó chính là 108 Anh hùng Lương Sơn Bạc. 
    Bên cạnh việc xây dựng rất thành công hàng loạt nhân vật anh hùng hảo hán, Thủy Hử hấp dẫn người đọc còn ở cách kể chuyện gần gũi với truyện kể dân gian. Giáo sư Lương Duy Thứ đã nhận xét: “…Văn chương của Thủy Hử không "dệt gấm thêu hoa" như Tây Sương ký, không "nhả ngọc phun châu" như Hồng Lâu Mộng, mà là "nhạc trỗi chuông ngân", hùng hồn, dồn dập... Tác phẩm Thủy Hử giữ được tính sống động của nhân vật trong ngôn ngữ, gần gũi với đời sống hằng ngày, trong lối hành văn ít trang sức tô điểm."
    Ở nước ta, bản dịch Thủy Hử của Á Nam Trần Tuấn Khải được nhiều người yêu thích bởi văn phong hàn lâm, trau chuốt. Á Nam Trần Tuấn Khải đã dịch từ bản Thủy Hử gồm 70 hồi chính truyện, 140 câu đề mục do Kim Thánh Thán - một nhà phê bình nổi tiếng đời Thanh soạn lại. Đây là bản Thủy Hử phổ biến nhất, giữ được tinh hoa cốt truyện, văn chương được gọt dũa, nhuận sắc.`,'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/thuy-hu-tron-bo-2-tap.jpg?v=1541082808883'),
    new Book('Tiếng Hàn tổng hợp dành cho người Việt Nam – Trung cấp 3', 'đại học quốc gia hà nội', 'Lê Thị Thu Giang, Đỗ Ngọc Luyến, Lee Mi Hye', 'ngoại ngữ', 210, `Giáo trình tiếng Hàn trung cấp 3 (bản mới) gồm 15 bài tương ứng với 15 chủ đề thông dụng được sắp xếp một cách có hệ thống và liên quan đến nhau. Cấu trúc mỗi bài được chia thành các phần rõ ràng : Từ vựng, cấu trúc ngữ pháp kèm ví dụ chi tiết, luyện nói, nghe, đọc, viết, văn hóa và cuối bài có kèm từ mới xuất hiện trong bài đọc: 
    Mở đầu mỗi bài có phần tóm tắt mục tiêu cho người học về kỹ năng, từ vựng, ngữ pháp, văn hóa…nhằm định hướng người học cần phải học như thế nào để đạt hiệu quả cao nhất.
    Từ vựng: Đưa ra các từ thông dụng trong cuộc sống hàng ngày tương ứng với chủ đề của bài
    Ngữ pháp: Mỗi bài học có từ 3 – 4 cấu trúc, giải thích bằng tiếng Việt chi tiết, cụ thể, kèm ví dụ thực tiễn giúp người học hiểu sâu ngữ pháp và luyện tập
    Luyện nói : Gồm các tình huống thông dụng trong cuộc sống, được chia làm 3 bước cơ bản : Làm quen – luyện tập – nâng cao
    Luyện nghe : Phần nghe kết hợp giữa nghe và chọn đáp án đúng, được sắp xếp theo trình tự từ dễ đến khó.
    Luyện đọc : Gồm các bài đọc từ cơ bản đến nâng cao giúp người học rèn luyện kỹ năng đọc và dịch.
    Luyện viết: Gồm các dạng bài : dịch từ tiếng Việt sang tiếng Hàn, điền từ vào chỗ trống và bài viết nâng cao
    Phần văn hóa : Giúp người học hiểu hơn về văn hóa truyền thống và hiện đại của Hàn Quốc
    Cuối mỗi bài sẽ có phần bổ sung từ vựng thường xuất hiện trong vid dụ và bài đọc`, 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/1-ad2bc937-731a-4286-8f60-14e4ed639869.jpg?v=1634612916430'),
    new Book('Tiếng Hàn tổng hợp trung cấp 4', 'đại học quốc gia hà nội', 'Lê Thị Thu Giang, Đỗ Ngọc Luyến, Lee Mi Hye', 'ngoại ngữ', 210, `Giáo trình tiếng Hàn trung cấp 4 (bản mới) gồm 15 bài tương ứng với 15 chủ đề thông dụng được sắp xếp một cách có hệ thống và liên quan đến nhau. Cấu trúc mỗi bài được chia thành các phần rõ ràng: Từ vựng, cấu trúc ngữ pháp kèm ví dụ chi tiết, luyện nói, luyện nghe, luyện đọc, luyện viết, văn hóa và cuối bài có kèm từ mới xuất hiện trong bài đọc: 
    Mở đầu mỗi bài có phần tóm tắt mục tiêu cho người học về kỹ năng, từ vựng, ngữ pháp, văn hóa…nhằm định hướng người học cần phải học như thế nào để đạt hiệu quả cao nhất.
    Từ vựng: Đưa ra các từ thông dụng trong cuộc sống hàng ngày tương ứng với chủ đề của bài
    Ngữ pháp: Mỗi bài học có từ 3 – 4 cấu trúc, giải thích bằng tiếng Việt chi tiết, cụ thể, kèm ví dụ thực tiễn giúp người học hiểu sâu ngữ pháp và luyện tập
    Luyện nói: Gồm các tình huống thông dụng trong cuộc sống, được chia làm 3 bước cơ bản: Làm quen – luyện tập – nâng cao
    Luyện nghe: Phần nghe kết hợp giữa nghe và chọn đáp án đúng, được sắp xếp theo trình tự từ dễ đến khó.
    Luyện đọc: Gồm các bài đọc từ cơ bản đến nâng cao giúp người học rèn luyện kỹ năng đọc và dịch.
    Luyện viết: Gồm các dạng bài : dịch từ tiếng Việt sang tiếng Hàn, điền từ vào chỗ trống và bài viết nâng cao
    Phần văn hóa: Giúp người học hiểu hơn về văn hóa truyền thống và hiện đại của Hàn Quốc
    Cuối mỗi bài sẽ có phần bổ sung từ vựng thường xuất hiện trong ví dụ và bài đọc
    Nội dung bài học trong quyển tiếng hàn trung cấp 4 có các biểu hiện thông dụng trong thực tiễn giúp người học dễ dàng ứng dụng trong cuộc sống hàng ngày.`, 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/1-afd06946-aeca-450b-ad95-afac0112f2f1.jpg?v=1634613335017'),
    new Book('Tiếng Hàn tổng hợp cao cấp 5', 'đại học quốc gia hà nội', 'Lê Thị Thu Giang, Đỗ Ngọc Luyến, Lee Mi Hye', 'ngoại ngữ', 210, `Giáo trình tiếng Hàn cao cấp 5 (bản mới) gồm 15 bài tương ứng với 15 chủ đề thông dụng được sắp xếp một cách có hệ thống và liên quan đến nhau. Cấu trúc mỗi bài được chia thành các phần rõ ràng: Từ vựng, cấu trúc ngữ pháp kèm ví dụ chi tiết, luyện nói, luyện nghe, luyện đọc, luyện viết, văn hóa và cuối bài có kèm từ mới xuất hiện trong bài đọc: 
    Mở đầu mỗi bài có phần tóm tắt mục tiêu cho người học về kỹ năng, từ vựng, ngữ pháp, văn hóa…nhằm định hướng người học cần phải học như thế nào để đạt hiệu quả cao nhất.
    Từ vựng: Đưa ra các từ thông dụng trong cuộc sống hàng ngày tương ứng với chủ đề của bài
    Ngữ pháp: Mỗi bài học có từ 3 – 4 cấu trúc, giải thích bằng tiếng Việt chi tiết, cụ thể, kèm ví dụ thực tiễn giúp người học hiểu sâu ngữ pháp và luyện tập
    Luyện nói: Gồm các tình huống thông dụng trong cuộc sống, được chia làm 3 bước cơ bản: Làm quen – luyện tập – nâng cao
    Luyện nghe: Phần nghe kết hợp giữa nghe và chọn đáp án đúng, được sắp xếp theo trình tự từ dễ đến khó.
    Luyện đọc: Gồm các bài đọc từ cơ bản đến nâng cao giúp người học rèn luyện kỹ năng đọc và dịch.
    Luyện viết: Gồm các dạng bài : dịch từ tiếng Việt sang tiếng Hàn, điền từ vào chỗ trống và bài viết nâng cao
    Phần văn hóa: Giúp người học hiểu hơn về văn hóa truyền thống và hiện đại của Hàn Quốc
    Cuối mỗi bài sẽ có phần bổ sung từ vựng thường xuất hiện trong ví dụ và bài đọc
    Nội dung bài học trong quyển tiếng hàn cao cấp 5 có các biểu hiện thông dụng trong thực tiễn giúp người học dễ dàng ứng dụng trong cuộc sống hàng ngày.`, 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/1-f71e53c9-f679-425a-a6d3-44d00a40514f.jpg?v=1634613649633'),
    new Book('Tiếng Hàn tổng hợp cao cấp 6', 'đại học quốc gia hà nội', 'Lê Thị Thu Giang, Đỗ Ngọc Luyến, Lee Mi Hye', 'ngoại ngữ', 220, `Giáo trình tiếng Hàn cao cấp 6 (bản mới) gồm 15 bài tương ứng với 15 chủ đề thông dụng được sắp xếp một cách có hệ thống và liên quan đến nhau. Cấu trúc mỗi bài được chia thành các phần rõ ràng: Từ vựng, cấu trúc ngữ pháp kèm ví dụ chi tiết, luyện nói, luyện nghe, luyện đọc, luyện viết, văn hóa và cuối bài có kèm từ mới xuất hiện trong bài đọc: 
    Mở đầu mỗi bài có phần tóm tắt mục tiêu cho người học về kỹ năng, từ vựng, ngữ pháp, văn hóa…nhằm định hướng người học cần phải học như thế nào để đạt hiệu quả cao nhất.
    Từ vựng: Đưa ra các từ thông dụng trong cuộc sống hàng ngày tương ứng với chủ đề của bài
    Ngữ pháp: Mỗi bài học có từ 3 – 4 cấu trúc, giải thích bằng tiếng Việt chi tiết, cụ thể, kèm ví dụ thực tiễn giúp người học hiểu sâu ngữ pháp và luyện tập
    Luyện nói: Gồm các tình huống thông dụng trong cuộc sống, được chia làm 3 bước cơ bản: Làm quen – luyện tập – nâng cao
    Luyện nghe: Phần nghe kết hợp giữa nghe và chọn đáp án đúng, được sắp xếp theo trình tự từ dễ đến khó.
    Luyện đọc: Gồm các bài đọc từ cơ bản đến nâng cao giúp người học rèn luyện kỹ năng đọc và dịch.
    Luyện viết: Gồm các dạng bài : dịch từ tiếng Việt sang tiếng Hàn, điền từ vào chỗ trống và bài viết nâng cao
    Phần văn hóa: Giúp người học hiểu hơn về văn hóa truyền thống và hiện đại của Hàn Quốc
    Cuối mỗi bài sẽ có phần bổ sung từ vựng thường xuất hiện trong ví dụ và bài đọc
    Nội dung bài học trong quyển tiếng hàn cao cấp 6 có các biểu hiện thông dụng trong thực tiễn giúp người học dễ dàng ứng dụng trong cuộc sống hàng ngày.
    Bố cục rõ ràng, hình ảnh, hình vẽ sinh động, màu sắc hài hòa kích thích sự tiếp thu và giúp việc học trở nên thú vị, không nhàm chán. 
    Nắm vững kiến thức trong giáo trình tương đương trình độ TOPIK cấp 6`,'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/1-6a995005-a2ae-4459-8fb2-a3ef6903f918.jpg?v=1634616440230'),
    new Book('Con chó nhỏ mang giỏ hoa hồng', 'trẻ', 'Nguyễn Nhật Ánh', 'văn học việt nam', 163, `Cái tựa sách quả là có sức gợi tò mò.Tại sao lại là con chó mang giỏ hoa hồng? Nó mang cho bạn nó, hay cho những ai biết yêu thương nó? 
    Câu chuyện về 5 chú chó đầy thú vị và cũng không kém cảm xúc lãng mạn- tác phẩm mới nhất của nhà văn bestseller Nguyễn Nhật Ánh sẽ khiến bạn thay đổi nhiều trong cách nhìn về loài thú cưng số 1 thế giới này.`, 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/con-cho-nho-mang-gio-hoa-hong.jpg?v=1544239971837'),  
    new Book(`Bảy bước tới mùa hè`, 'trẻ', 'Nguyễn Nhật Ánh', 'văn học việt nam', 84, `Bảy bước tới mùa hè là tác phẩm mới nhất của Nguyễn Nhật Ánh, được nhà văn đề tặng "Những năm ấu thơ", như một món quà dành tặng các bạn đọc thân thiết của mình nhân dịp đầu năm mới.
    Câu chuyện về một mùa hè ngọt ngào, những trò chơi nghịch ngợm và bâng khuâng tình cảm tuổi mới lớn. Chỉ vậy thôi nhưng chứng tỏ tác giả đúng là nhà kể chuyện hóm hỉnh, khiến độc giả cuốn hút từ trang đầu đến trang cuối cùng. Chúng ta sẽ bắt gặp giọng văn giản dị, trong trẻo của nhà văn Nguyễn Nhật Ánh và một kết thúc có hậu đầy thuyết phục ở cuối truyện. Câu chuyện về tuổi học trò đầy ắp những kỷ niệm thơ bé ngọt ngào với tình thầy trò, bè bạn, tình xóm giềng, họ hàng qua cách nhìn đời nhẹ nhàng, rộng lượng.
    Nhà văn chia sẻ: "Tôi thích sự vui tươi của câu chuyện và sự hồn nhiên của nhân vật. Có thể nói đây là tác phẩm đầy ắp tiếng cười. Tạm thời xa rời những trang văn chứa nhiều chiêm nghiệm của người lớn, qua tác phẩm này tôi muốn quay trở lại lối viết mà tác giả không cố ý để lại quá nhiều dấu tay trên bản thảo. Tác giả trong tác phẩm này cũng đang ở… tuổi mười lăm!"`, 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/bay-buoc-toi-mua-he.jpg?v=1541082759010'),
    new Book('Bộ sách ở nơi xa tít mù khơi', 'Kim Đồng', 'Toon Tellegen', 'thiếu nhi', 160, `Ở Nơi Xa Tít Mù Khơi Sáng nọ, gió thổi một lá thư lọt qua khe cửa nhà Sóc. Bì thư màu xanh dương thoảng mùi muối mặn. Dường như lá thư đến từ một nơi xa lắm, xa tít mù khơi. Sóc bóc thư: “Sóc ơi, Bằng những dòng chữ cậu đang đọc đây, tớ chúc cậu mọi điều tốt đẹp nhất. Tớ hi vọng lá thư này sẽ làm cậu cảm động, biết đâu cậu còn phải lau những giọt nước mắt chứa chan vì hạnh phúc. Khỏi cần hồi âm, hãy tận hưởng những lời thư của tớ. Tớ nhiệt thành mong cậu sẽ nhận được nhiều nữa những lá thư thế này. Chim Thiên Đường nhún nhường của cậu.” Những câu chuyện thú vị ở thế giới kì diệu bao la, nơi bất cứ điều gì cũng có thể xảy ra: Ốc Sên bay lượn, bầu trời xanh lục, cây cối vươn mình đứng dậy và giận dỗi bỏ đi. Những câu chuyện tuyệt diệu được điểm tô hoàn hảo bởi minh họa tinh tế của Jessica Ahlberg chắc chắn sẽ làm say lòng bạn đọc mọi lứa tuổi. “Lối kể chuyện khác thường, sâu lắng cùng cách tiếp cận nhẹ nhàng của Toon Tellegen mê hoặc bất cứ ai từng đọc những mẩu ngụ ngôn nên thơ này.”`, 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/1-9e89b234-8708-4f52-80f8-12810f3e5558.jpg?v=1634270372130'),
    new Book('Chiến binh cầu vồng', 'hội nhà văn', 'Andrea Hirata','văn học nước ngoài' , 85, `Một tác phẩm có tầm ảnh hưởng sâu rộng nhất Indonesia.

    “Thầy Harfan và cô Mus nghèo khổ đã mang đến cho tôi tuổi thơ đẹp nhất, tình bạn đẹp nhất, và tâm hồn phong phú, một thứ gì đó vô giá, thậm chí còn có giá trị hơn những khao khát mơ ước. Có thể tôi lầm, nhưng theo ý tôi, đây thật sự là hơi thở của giáo dục và linh hồn của một chốn được gọi là trường học.” - (Trích tác phẩm)
    
    Trong ngày khai giảng, nhờ sự xuất hiện vào phút chót của cậu bé thiểu năng trí tuệ Harun, trường Muhammadiyah may mắn thoát khỏi nguy cơ đóng cửa. Nhưng ước mơ dạy và học trong ngôi trường Hồi giáo ấy liệu sẽ đi về đâu, khi ngôi trường xập xệ dường như sẵn sàng sụp xuống bất cứ lúc nào, khi lời đe dọa đóng cửa từ viên thanh tra giáo dục luôn lơ lửng trên đầu, khi những cỗ máy xúc hung dữ đang chực chờ xới tung ngôi trường để dò mạch thiếc…? Và liệu niềm đam mê học tập của những Chiến binh Cầu vồng đó có đủ sức chinh phục quãng đường ngày ngày đạp xe bốn mươi cây số, rồi đầm cá sấu lúc nhúc bọn ăn thịt người, chưa kể sự mê hoặc từ những chuyến phiêu lưu chết người theo tiếng gọi của ngài pháp sư bí ẩn trên đảo Hải Tặc, cùng sức cám dỗ khôn cưỡng từ những đồng tiền còm kiếm được nhờ công việc cu li toàn thời gian ...?
    
    Chiến binh Cầu vồng có cả trong sáng tuổi học trò lẫn những trò đùa tinh quái, cả nước mắt lẫn tiếng cười – một bức tranh chân thực về hố sâu ngăn cách giàu nghèo, một tác phẩm văn học cảm động truyền tải sâu sắc nhất ý nghĩa đích thực của việc làm thầy, việc làm trò và việc học.
    
    Tác phẩm đã bán được trên năm triệu bản, được dịch ra 26 thứ tiếng, là một trong những đại diện xuất sắc nhất của văn học Indonesia hiện đại.`, 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/chien-binh-cau-vong.jpg?v=1542789091933'),
    new Book('Khi mọi điểm tựa đều mất', 'tổng hợp thành phố hồ chí minh', 'Marci Shimoff, Carol Kline', 'kỹ năng - sống đẹp', 59.5, `Với Happy for No Reason – Khi mọi điểm tựa đều mất, tác giả Marci Shimoff đã có một cuộc cách mạng về quan niệm hạnh phúc. Trong khi phần lớn những quyển sách ở thể loại này hướng vào việc giúp con người tìm kiếm hạnh phúc từ những yếu tố bên ngoài thì Happy for No Reason lại hướng vào những yếu tố nội tâm. Nhờ vậy, bạn sẽ tìm thấy những phương thức tuy đơn giản nhưng lại rất hữu hiệu giúp bạn trải nghiệm một cảm xúc mới – hạnh phúc tự thân – bất kể mọi tác động tiêu cực từ bên ngoài. Quyển sách sẽ gửi đến bạn nền tảng cơ bản nhất, giúp bạn duy trì một trạng thái hạnh phúc bền vững và trọn vẹn.
    Thông qua một nghiên cứu được trình bày trong cuốn sách chúng ta nhận ra rằng: 50% giới hạn hạnh phúc được quy định do kiểu gen, phần còn lại là do chúng ta tích lũy. Và trong 50% còn lại chỉ 10% trong số đó là phụ thuộc vào những yếu tố như: sự giàu có, tình trạng hôn nhân và công việc; còn 40% cuối cùng là kết quả của những suy nghĩ, cảm giác, ngôn từ và hành động của con người.
    Đọc cuốn sách để thấy rằng hạnh phúc là điều vô cùng giản dị và gần gũi bởi vì nó ở ngay bên trong mỗi chúng ta, ta không đi tìm hoặc nắm bắt hạnh phúc mà chúng ta rèn luyện để có được hạnh phúc. Vì vậy chúng ta hãy ngưng việc theo đuổi một điều không có kết quả và tốt hơn là nên bắt đầu rèn luyện để có được hạnh phúc bằng cách hình thành và trau dồi những thói quen.
    Những trải nghiệm có thật trong cuộc sống cũng như những nghiên cứu của tác giả đã ảnh hưởng đến suy nghĩ của tác giả về hạnh phúc. Theo đó, có bảy bước rất đơn giản giúp bạn trải nghiệm niềm hạnh phúc đích thực. Với hình ảnh Ngôi nhà ẩn dụ cho cuộc sống con người, tác giả đã mượn hình ảnh này làm biểu tượng cho ý tưởng của mình: bảy bước để xây dựng “ngôi nhà hạnh phúc”. Bảy bước này có liên quan đến bảy đối tượng mà bạn cần quan tâm trong cuộc sống của mình: sức mạnh bản thân, tinh thần, con tim, cơ thể, tâm hồn, mục tiêu và con người.`, 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/khi-moi-diem-tua-deu-mat.jpg?v=1542797599487'),
    new Book('Từ điển Oxford Anh Anh Việt', 'đại học quốc gia hà nội', 'Oxford', 'Từ điển', 200, `
    Bạn là người đã có nền tảng cơ bản về ngữ âm, ngữ pháp nhưng vốn từ vựng lại ít?    
    Bạn là người tự tin trong giao tiếp tiếng anh nhưng đôi khi không thể truyền tải hết ý của mình vì thiếu vốn từ?
    Bạn là người đã có nhiều vốn từ nhưng chưa thực sự áp dụng được vốn từ đó trong giao tiếp thực tế?
    Bạn là dân chuyên anh và mong muốn có được một cuốn từ điển chuyên nghiệp nhất hiện nay?
    Bạn là người thích học từ mới nhưng chưa tìm được cho mình một tài liệu nào truyền được nhiều cảm hứng học tập?
    Với cuốn từ điển “Oxford Anh-Anh-Việt” trên tay, chúng tôi sẽ giúp bạn có được:
    -Khối lượng vốn từ vựng phong phú, cập nhật tất cả những từ ngữ thông dụng hiện đại
    -Nắm bắt được những cụm từ tiếng Anh cùng với văn phạm và từ vựng mang tính thực tiễn cao.
    -Ghi nhớ được văn phạm và từ vựng một cách hoàn toàn tự nhiên.
    -Thâu tóm được các mẫu câu thông dụng, dễ hiểu có thể áp dụng ngay trong giao tiếp hàng ngày.
    -Nắm bắt được vô số cấu trúc câu chuyên ngành dành riêng cho mỗi từ vựng
    -Phát âm chuẩn xác như một chuyên gia ngôn ngữ hàng đầu thế giới
    -Tạo cảm hứng học tiếng Anh và vô cùng thích thú với việc hoc từ mới.
    -Phong cách truyền tải kiến thức cực kỳ dễ hiểu và nhanh chóng đi vào trí nhớ của bạn.
    Cuốn Từ điển “Oxford Anh – Anh – Việt“ được công ty cổ phần sách MCBooks liên kết xuất bản và phát hành tại Việt Nam. Cuốn Từ điển này hiện đang trở thành một làn sóng mới trên thị trường cả nước với doanh thu khổng lồ, hiện cuốn sách đang được đánh giá là cuốn từ điển chất lượng và có tính thẩm mỹ cao nhất hiện nay.
    
    Từ điển “Oxford Anh-Anh-Việt” của MCBooks có 2 mẫu mã, 2 màu sắc, 2 loại bìa cứng và mềm cho bạn lựa chọn. Với hơn 350.000 từ được chọn lọc dựa trên phiên bản mới nhất của Oxford và Cambridge, thêm 85 phụ lục – từ điển bằng tranh đặc sắc chia theo nhiều chủ đề.
    
    Đây là cuốn từ điển tiếng Anh được biên dịch dựa theo cuốn từ điển Oxford, Cambridge và một số cuốn từ điển uy tín nhất trên thế giới, một công trình liên tục được đổi mới, được công bố bởi nhà xuất bản hàng đầu thế giới và nay đã có mặt tại Việt Nam, trợ giúp cho các nhà nghiên cứu, các giảng viên, đặc biệt là sinh viên Việt Nam nhiều thập kỷ qua.
    
    Từ điển “Oxford Anh-Anh-Việt“ của MCBooks không chỉ là một cuốn từ điển, mà còn là một tác phẩm nghệ thuật, một công trình khoa học được đầu tư bài bản:
    -Bìa sách và nội dụng được in ấn với gam màu ấn tượng, trang trí sinh động. Phần phụ lục bằng tranh đặc sắc, học từ vựng vừa qua từ vừa qua hình ảnh
    -85 trang phụ lục – từ điển bằng tranh đặc sắc chia theo nhiều chủ đề: Nông thôn, thành thị, vùng núi động vật.
    –Từ điển Oxford được biên soạn phù hợp nhất với Học sinh, Sinh viên Việt Nam về cả chất lượng nội dung lẫn hình thức.
    
    -Anh: Những từ được chọn lọc, phát triển trên nền Oxford và Cambridge, lược bỏ các từ cổ người Anh – Mỹ ít dùng. Phiên âm chuẩn, lý tưởng hơn là phiên âm dựa trên bảng mẫu tự phiên âm Quốc tế (International Phonetic Alphabet – IPA). Đây là bảng mẫu tự chuẩn được sử dụng bởi các chuyên gia ngôn ngữ trên toàn Thế giới.
    
    -Anh: Giải thích từ bằng mẫu kết cấu câu phổ dụng, rõ ràng, chính xác, phù hợp giúp người học sử dụng được ngôn ngữ đích. Các định nghĩa bằng Tiếng Anh giúp bạn học được sâu và rộng hơn. Bạn sẽ bắt gặp một số từ thường xuyên hơn vì nó xuất hiện trong định nghĩa của những từ khác.
    
    -Việt: Giải thích và chuyển nghĩa chính xác trung thành với nguyên bản tiếng anh, phần dịch đạt độ chính xác tới mức cao nhất . Có rất nhiều mẫu câu ví dụ, định nghĩa rất dễ hiểu cho từ vựng, chọn lọc những câu gắn với cấu trúc thông dụng.
    
    -Công trình được sự tham gia tu chỉnh hiệu đính PGS. TS. Lâm Quang Đông ( Trưởng khoa Anh, trường đại học Ngoại Ngữ, đại học Quốc Gia) cùng toàn thể giáo viên trường đại học Ngoại Ngữ, đại học Quốc Gia – trường ngoại ngữ hàng đầu Việt Nam.
    
    Chúng tôi tin rằng Quý độc giả sẽ cảm thấy có một sự lựa chọn đúng đắn khi cầm trên tay cuốn từ điển này, một quyển sách không chỉ để nâng cao trình độ tiếng Anh, mà là phương pháp học thoải mái và cực kì hiệu quả. Hãy biến nó thành một cuốn cẩm nang gối đầu giường của bạn.
    Chúc bạn thành công, hạnh phúc, giỏi tiếng anh, thanh thản và thành đạt.`, 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/tu-dien-anh-anh-viet-bia-cung-vang.jpg?v=1542245252753'),
    new Book('Gieo hạt giống thương yêu', 'hà nội', 'Caroline Jayne Church', 'thiếu nhi', 128, `Gieo hạt giống thương yêu (8 tập) là một bộ sách rất dễ thương và thú vị với nội dung viết về tình cảm gia đình và bạn bè vô cùng gần gũi và ấm áp, ngôn ngữ kể chuyện nhẹ nhàng và tình cảm, hình ảnh ngộ nghĩnh và đáng yê chắc chắn sẽ mang lại những giây phút vui vẻ cùng nhiều khoảnh khắc tuyệt vời cho bố mẹ và các em bé.
    Bộ sách siêu ấm áp và ngọt ngào này giống như món quà tặng quý giá, sẽ giúp nuôi dưỡng và vun đắp những "hạt giống thương yêu" giữa bố mẹ, anh chị em, bạn bè của các em bé trong chính ngôi nhà thân yêu của mình.`, 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/1-aa4a2e77-4556-48ff-be3f-fb16be0b99fb.jpg?v=1632736245483', 20),
    new Book('Đồng giao cho bé', 'kim đồng', 'Hiếu Minh', 'thiếu nhi', 81, `Đồng dao là những câu hát dân gian mà trẻ em hát lúc vui chơi. Lời hát đồng dao gắn liền với các trò chơi. Không chỉ là trò chơi vui, mang tính chất rèn luyện phản xạ, vận động ở tất cả các giác quan cho trẻ, các bài hát đồng dao có giai điệu vui tươi, giàu hình ảnh còn là những bài học giáo dục đạo đức, phát triển ngôn ngữ, tư duy cho các em. Bởi vậy, xưa cho đến nay, đồng dao vẫn luôn được trẻ em thuộc và hát lên hằng ngày.
    Mời các bạn tìm đọc bộ Đồng Dao Cho Bé:
    Chi Chi Chành Chành - Trò Chơi Dân Dã
    Ông Trẳng Ông Trăng - Bài Học Lí Thú
    Nựng Nựng Nà Nà - Câu Hát Yêu Thương`, 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/anh-3c.jpg?v=1626227947947', 15),
    new Book('câu đố tư duy', 'phụ nữ việt nam', 'Pingbooks', 'thiếu nhi', 80, `Bố mẹ nào vừa muốn con phát triển ngôn ngữ, vừa rèn luyện khả năng tư duy lại vừa phát triển trí tưởng tượng thì rinh ngay cuốn này nhé. Sách dạng giấy cứng, màu sắc đẹp, bắt mắt, minh họa dễ thương. Các câu đố dưới dạng thơ, có vần có điệu, nghe vui vẻ rủng rẻng… Toàn những thứ quen thuộc, gần gũi xung quanh các bé: con vịt, con bò, con mèo, gà con, thỏ con, bốn mùa, cầu vồng….túm lại là VUI MẮT, VUI TAI, VUI TAY, VUI MIỆNG…`, 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/1-65709f08-7acd-4f64-b026-7bc53186f97c.jpg?v=1621397919290'),
    new Book('Bố già', 'á đông', 'Mario Puzo', 'văn học nước ngoài', 127.5, `Thế giới ngầm được phản ánh trong tiểu thuyết Bố già là sự gặp gỡ giữa một bên là ý chí cương cường và nền tảng gia tộc chặt chẽ theo truyền thống Mafia xứ Sicily với một bên là xã hội Mỹ nhập nhằng đen trắng, mảnh đất màu mỡ cho những cơ hội làm ăn bất chính hứa hẹn những món lợi kếch xù. Trong thế giới ấy, hình tượng Bố già được tác giả dày công khắc họa đã trở thành bức chân dung bất hủ trong lòng người đọc.
    Từ một kẻ nhập cư tay trắng đến ông trùm tột đỉnh quyền uy, Don Vito Corleone là con rắn hổ mang thâm trầm, nguy hiểm khiến kẻ thù phải kiềng nể, e dè, nhưng cũng được bạn bè, thân quyến xem như một đấng toàn năng đầy nghĩa khí. Nhân vật trung tâm ấy đồng thời cũng là hiện thân của một pho triết lí rất “đời” được nhào nặn từ vốn sống của hàng chục năm lăn lộn giữa chốn giang hồ bao phen vào sinh ra tử.
    Với kết cấu hoàn hảo, cốt truyện không thiếu những pha hành động gay cấn, tình tiết bất ngờ và không khí kình địch đến nghẹt thở, Bố già xứng đáng là đỉnh cao trong sự nghiệp văn chương của Mario Puzo.`, 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/bo-gia.jpg?v=1542852073310', 100),
    new Book('Khi lỗi thuộc vì những vì sao', 'trẻ', 'John Green', 'văn học nước ngoài', 89.5, `Mặc dù phép màu y học đã giúp thu hẹp khối u và ban thêm vài năm sống cho Hazel nhưng cuộc đời cô bé đang ở vào giai đoạn cuối, từng chương kế tiếp được viết theo kết quả chẩn đoán. Nhưng khi có một nhân vật điển trai tên là Augustus Waters đột nhiên xuất hiện tại Hội Tương Trợ Bệnh Nhi Ung Thư, câu chuyện của Hazel sắp được viết lại hoàn toàn.
    Sâu sắc, táo bạo, ngang tàng, và thô ráp, Khi lỗi thuộc về những vì sao là tác phẩm thương tâm và tham vọng nhất của John Green, tác giả của những giải thưởng, nhưng đồng thời lại khám phá một cách khéo léo nét hài hước, li kỳ, và bi thảm của việc sống và việc yêu.`, 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/khi-loi-thuoc-ve-nhung-vi-sao.jpg?v=1542790495537', 28),
    new Book('Chuyện con mèo dạy hải âu bay', 'hội nhà văn', 'Luis Sepúlveda', 'văn học nước ngoài', 35, `Có tồn tại không tình thương yêu giữa mèo và hải âu?
    Thế giới này đầy những nghịch lý và khác biệt, nhưng bỏ qua những khác biệt đó để hướng đến tình yêu thương thì cuộc sống sẽ tốt đẹp hơn.“Chuyện con mèo dạy hải âu bay” của nhà văn Chi Lê nổi tiếng Luis SéPulveda.là một câu chuyện thấm đẫm tình mèo, tình người như thế.
    Câu chuyện là cuộc hành trình dài đi thực hiện ba lời hứa của chú mèo mập Zorba: “sẽ không ăn quả trứng”, sẽ “chăm lo cho quả trứng đến khi chú chim non ra đời”, và điều cuối dường như không tưởng là “dạy nó bay”. Những rắc rối liên tiếp ập đến, liệu một bà má rất “xịn” như Zorba có thực hiện đúng được ba lời hứa?
    Tình thương giúp thay đổi định kiến.
    Mọi khó khăn đã chứng minh rằng sau thẳm bên trong chú mèo Zorba là một trái tim nhân hậu, tràn trề thứ tình cảm gọi là “yêu thương chân thành”. Chính thứ tình cảm này đã kéo cô bé chim hải âu nhỏ gần lại với mèo Zorba, bởi “Thật dễ dàng để chấp nhận và yêu thương một kẻ nào đó giống mình, nhưng để yêu thương ai đó khác mình thực sự rất khó khăn..”. Vậy đấy, yêu thương là học cách chấp nhận sự khác biệt và không có ý định muốn biến người đó trở nên giống mình. Khi chúng ta yêu thương ai đó bằng tất cả sự chân thành, thì mọi định kiến và khác biệt chỉ là điểm tựa cho tình cảm cao đẹp trong loài mèo, loài người ấy được sâu sắc hơn thôi.`, 'https://bizweb.dktcdn.net/thumb/1024x1024/100/335/968/products/chuyen-con-meo-day-hai-au-bay.jpg?v=1542789606807', 39)
];
// user1.cart.addNewItemIntoCart(new CartItem(5, booksList[5], 1));